all:
	python plot_pot.py -o ../Figure5.pdf
	python plot_pot_er.py -o ../Figure6.pdf
	python plot_pot_solv.py -o ../Figure7.pdf
	python plot_pot_DH.py -o ../Figure8.pdf
	python  plot_cplx_Kx1.py -o ../Figure9.pdf
	python  plot_cplx_Kx2.py -o ../Figure10.pdf
	python plot_pot_hammet.py -o ../FigureS1.pdf
