all:
	python plot_pot.py -o ../Figure8.pdf
	python plot_pot_er.py -o ../Figure9.pdf
	python plot_pot_solv.py -o ../Figure10.pdf
	python plot_pot_DH.py -o ../Figure11.pdf
	python  plot_cplx_Kx1.py -o ../Figure12.pdf
	python  plot_cplx_Kx2.py -o ../Figure14.pdf
	python  plot_pot_exp.py -o ../Figure15.pdf
	python  plot_pot_matsui.py -o ../Figure15.pdf
	python plot_DH.py -o ../FigureS1.pdf
	python plot_CIP.py -o ../FigureS2.pdf
	python plot_pairs.py -o ../FigureS3.pdf
	python plot_pot_vs_Hodgson.py -o ../FigureS4.pdf
	python plot_pot_hammet.py -o ../FigureS5.pdf
	python plot_cplx_Gx1.py -o ../FigureS6.pdf
